name: CI
on:
  push:
  pull_request:
jobs:
  golangci:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0
  vertify:
    name: Vertify vendor, codegen, crds
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      WORKSPACE: ${{ github.workspace }}/src/github.com/clusterpedia-io/clusterpedia
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: hack/verify-vendor.sh
      - run: hack/verify-codegen.sh
      - run: hack/verify-crds.sh
  build:
    name: Build
    needs: vertify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Compile
        run: make all
  test:
    name: Unit test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make test
