name: Sync Api
on:
  push:
#     TODO 在测试分支测试
    branches:
      - sync-api
#    TODO 需要确认打tag时是否需要对api改动后才同步tag
    tags:
      - v*
    paths:
      - 'staging/src/github.com/clusterpedia-io/api/*'
jobs:
  sync-api:
    name: Sync Api
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{ github.workspace }}/src/github.com/clusterpedia-io/clusterpedia
      APIREPOTOKEN: ${{ secrets.ACCESS_TOKEN }}
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      - name: Checkout code
        run: hack/sync-api-test.sh
