name: Sync Api
on:
  push:
#     TODO 在测试分支测试
    branches:
      - sync-api
    tags:
      - v*
jobs:
  sync-api:
    name: Sync Api
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{ github.workspace }}/src/github.com/clusterpedia-io/clusterpedia
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKSPACE }}
      - name: Sync code
        with:
        token: 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
      - run: echo ${{ github.actor }}
      - run: hack/sync-api-test.sh
